# 1 поток = 1 параллельно выполняющаяся задача.
development:
  :concurrency: 1
# Считывается знач. переменной среды или 15.
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 15 %>
# Одна очередь на выполнение, с названием default.
:queues:
  - default
# Столько раз задача будет перевыполняться при возникновении ошибки.
:max_retries: 1
